
import Project.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kirubaharan
 */
public class customer_login extends javax.swing.JFrame {

    /**
     * Creates new form customer_login
     */
    public customer_login() {
        initComponents();
    }
    void clear()
{
    Cuser.setText("");
    Cpass.setText("");
    
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cuser = new javax.swing.JTextField();
        Cpass = new javax.swing.JPasswordField();
        CustLogin = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        CustLogin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(215, 72, 61));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close all jframe.png"))); // NOI18N
        Cexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CexitActionPerformed(evt);
            }
        });
        getContentPane().add(Cexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 20, 60, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 290, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Enter_Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Enter_Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 336, 180, 60));
        getContentPane().add(Cuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 250, 340, 43));

        Cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpassActionPerformed(evt);
            }
        });
        getContentPane().add(Cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 340, 43));

        CustLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        CustLogin.setText("Login");
        CustLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustLoginActionPerformed(evt);
            }
        });
        getContentPane().add(CustLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 300, 42));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setText("Show_Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        CustLogin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        CustLogin1.setText("Sign Up");
        CustLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustLogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(CustLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 300, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpassActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            Cpass.setEchoChar((char) 0);
        } else {
            Cpass.setEchoChar('*');
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void CexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CexitActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
            // Set frame size to full screen
            login.setExtendedState(JFrame.MAXIMIZED_BOTH);
            login.setVisible(true); 
    }//GEN-LAST:event_CexitActionPerformed

    private void CustLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustLoginActionPerformed
        // TODO add your handling code here:
        String user1 = Cuser.getText();
        String pass1 = Cpass.getText();
        try {
            Connection con = (Connection) ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs;
            rs = st.executeQuery("select * from login where user='" + user1 + "'and pass='" + pass1 + "'");
            if (rs.next()) {
                Customer_Page cp=new Customer_Page();
                cp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                cp.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Incorrect username or password \n Login again or Sign up...!");
                clear();
            }
        } catch (HeadlessException | SQLException e) {
System.out.println(e);        }

    }//GEN-LAST:event_CustLoginActionPerformed

    private void CustLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustLogin1ActionPerformed
        // TODO add your handling code here:
        String user2=Cuser.getText();
        String pass2=Cpass.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.execute("insert into login values('"+user2+"','"+pass2+"')");
            
            JOptionPane.showMessageDialog(null,"New Acount Created for You....!!!");
            clear();
        }
            catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    

    }//GEN-LAST:event_CustLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
                customer_login cl=new customer_login();
                cl.setExtendedState(JFrame.MAXIMIZED_BOTH);
                cl.setVisible(true);
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cexit;
    private javax.swing.JPasswordField Cpass;
    private javax.swing.JTextField Cuser;
    private javax.swing.JButton CustLogin;
    private javax.swing.JButton CustLogin1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    
}
