
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kirubaharan
 */
public class Customer_Page extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Page
     */
    public Customer_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custExit = new javax.swing.JButton();
        Buyer = new javax.swing.JButton();
        Producer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 0));
        setFocusable(false);
        setLocation(new java.awt.Point(300, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close all jframe.png"))); // NOI18N
        custExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custExitActionPerformed(evt);
            }
        });
        getContentPane().add(custExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1386, 20, 60, 60));

        Buyer.setBackground(new java.awt.Color(0, 204, 204));
        Buyer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Buyer.setText("Buyer ");
        Buyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyerActionPerformed(evt);
            }
        });
        getContentPane().add(Buyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 590, 110));

        Producer.setBackground(new java.awt.Color(0, 153, 153));
        Producer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Producer.setText("Producer");
        Producer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducerActionPerformed(evt);
            }
        });
        getContentPane().add(Producer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 590, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custExitActionPerformed
        // TODO add your handling code here:
        customer_login cl=new customer_login();
                cl.setExtendedState(JFrame.MAXIMIZED_BOTH);
                cl.setVisible(true);
    }//GEN-LAST:event_custExitActionPerformed

    private void BuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyerActionPerformed
        // TODO add your handling code here:
        buyer b= new buyer();
                b.setExtendedState(JFrame.MAXIMIZED_BOTH);
                b.setVisible(true);
    }//GEN-LAST:event_BuyerActionPerformed

    private void ProducerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducerActionPerformed
        // TODO add your handling code here:
        producer p = new producer();
               p.setExtendedState(JFrame.MAXIMIZED_BOTH);
               p.setVisible(true);
    }//GEN-LAST:event_ProducerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
                Customer_Page cp=new Customer_Page();
                cp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                cp.setVisible(true);
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buyer;
    private javax.swing.JButton Producer;
    private javax.swing.JButton custExit;
    // End of variables declaration//GEN-END:variables
}
