
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kirubaharan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginExit = new javax.swing.JButton();
        Mlogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Clogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 1450, 640));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        loginExit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                loginExitComponentResized(evt);
            }
        });
        loginExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitActionPerformed(evt);
            }
        });
        getContentPane().add(loginExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 30, 70, 60));

        Mlogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Mlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new buyer.png"))); // NOI18N
        Mlogin.setText("Management Login");
        Mlogin.setAlignmentX(10);
        Mlogin.setAlignmentY(20);
        Mlogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        Mlogin.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        Mlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MloginActionPerformed(evt);
            }
        });
        getContentPane().add(Mlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 880, 140));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Clogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new buyer.png"))); // NOI18N
        Clogin.setText("Customer Login");
        Clogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        Clogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloginActionPerformed(evt);
            }
        });
        jPanel1.add(Clogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 890, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 390, 1580, 470));

        jPanel2.setBackground(new java.awt.Color(3, 197, 181));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1570, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloginActionPerformed
        // TODO add your handling code here:
        customer_login cl=new customer_login();
                cl.setExtendedState(JFrame.MAXIMIZED_BOTH);
                cl.setVisible(true);
    }//GEN-LAST:event_CloginActionPerformed

    private void loginExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to exit Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_loginExitActionPerformed

    private void loginExitComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_loginExitComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_loginExitComponentResized

    private void MloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MloginActionPerformed
              // TODO add your handling code here:
              Login_Page lp =new Login_Page();
               lp.setExtendedState(JFrame.MAXIMIZED_BOTH);
               lp.setVisible(true);
    }//GEN-LAST:event_MloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
            // Set frame size to full screen
            login.setExtendedState(JFrame.MAXIMIZED_BOTH);
            login.setVisible(true);            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clogin;
    private javax.swing.JButton Mlogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginExit;
    // End of variables declaration//GEN-END:variables
}
